# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2

updates:
  # Python dependencies
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly

  # GitHub workflow actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
