# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    pre_build:
      - cd docs && make satrecsv-copy
    post_build:
      # Check satre.xlsx was correctly copied
      - cd docs && make check-satrecsv

sphinx:
  configuration: docs/source/conf.py

formats:
  - epub
  - pdf

python:
  install:
    - requirements: docs/requirements.txt
